/* =============================================================================
   Events Penedès — textos de la portada en catalán e inglés
   El castellano vive en el HTML; el motor (js/i18n.js) lo lee al arrancar.
   ========================================================================== */
window.EP_I18N = {

    ca: {
      'ven.v3.alt': 'Sala de banquet de la Masia Torreblanca amb taules rodones i finestrals al camp',
      'ven.v3.alt2': 'Galeria d’arcs de pedra de la Masia Torreblanca, amb bigues de fusta i palmeres',
      'ven.v3.alt3': 'Pèrgola al costat de la piscina de la Masia Torreblanca, amb vistes a les vinyes',
      'ven.v5.alt': 'Jardí de La Torre del Gall de nit, amb taules sota els arbres i garlandes de llums',
      'ven.v5.alt2': 'Vista aèria de La Torre del Gall envoltada de vinyes i arbreda',
      'ven.v6.alt': 'Façana de Bellesguart amb les portes de fusta obertes sobre el menjador',
      'ven.v6.alt2': 'Torre modernista de Bellesguart sobre l’estany, entre vegetació',
      'ven.v6.alt3': 'Taula llarga de fusta sota llums de vidre al menjador de Bellesguart',
      'ven.v6.alt4': 'Vinya de Bellesguart amb Montserrat al fons',
      'svc.s8.tag': 'Premium',
      'svc.s8.title': 'Tast d’oli · D’Oliciós',
      'svc.s8.text': 'Tast d’oli d’oliva verge extra en un molí ecològic de l’Arboç, amb la premsa al costat i l’oli premiat que s’hi elabora. Funciona tot l’any, a diferència de la verema, i sorprèn fins i tot qui ja ha fet tres tasts de vi.',
      'svc.s8.i1': 'Tast guiat al mateix molí',
      'svc.s8.i2': 'Maridatges i àpats temàtics amb tòfona i oli',
      'svc.s8.i3': 'Es combina amb l’espai de Bellesguart, a la mateixa casa',
      'svc.s8.i4': 'Alternativa al tast de vi fora de temporada',
      'svc.s8.link': 'dolicios.com',
      'ven.l.aforo': 'Aforament màxim',
      'ven.l.events': 'Tipus d’acte',
      'ven.l.cuina': 'Cuina',
      'ven.l.reunio': 'Sales de reunió',
      'ven.v1.f1': '30 persones',
      'ven.v1.f2': 'Tasts, taller de castells, àpats a l’aire lliure',
      'ven.v1.f3': 'Barbacoa; el càtering entra de fora',
      'ven.v1.f4': 'No: només espai exterior',
      'ven.v2.f1': '50 persones',
      'ven.v2.f2': 'Team building i taller de castells',
      'ven.v2.f3': 'No; es combina amb un altre espai',
      'ven.v2.f4': 'No: espai obert',
      'ven.v2.web': 'teamtowers.eu',
      'ven.v3.f1': 'Fins a 500 persones',
      'ven.v3.f2': 'Convencions, presentacions, àpats d’empresa i casaments',
      'ven.v3.f3': 'Càtering en exclusiva de Cal Blay',
      'ven.v3.f4': 'Sí, diverses sales i la torre lateral',
      'ven.v3.web': 'masiatorreblanca.com',
      'ven.v5.tag': 'Espai aliat',
      'ven.v5.title': 'La Torre del Gall',
      'ven.v5.text': 'Finca del segle XV a Sant Cugat Sesgarrigues, amb cinc hectàrees de vinya pròpia, tres espais interiors i sis d’exteriors. És l’espai que resol una jornada sencera sense moure el grup: cuina pròpia a la mateixa finca, sales per reunir-se i exclusivitat de la finca a partir de 100 persones. A 40 minuts de Barcelona i 20 de Sitges.',
      'ven.v5.f1': '350 drets · 280 asseguts',
      'ven.v5.f2': 'Convencions, jornades d’empresa, banquets i calçotades',
      'ven.v5.f3': 'Pròpia, 700 m², a la mateixa finca',
      'ven.v5.f4': 'Sí, sales privades a la torre',
      'ven.v5.web': 'latorredelgall.com',
      'ven.v6.tag': 'Espai aliat',
      'ven.v6.title': 'Bellesguart',
      'ven.v6.text': 'Finca familiar en un edifici modernista del 1889, a l’Arboç, a menys de 45 minuts tant de Barcelona com de Tarragona. Comparteix casa amb el molí d’oli ecològic D’Oliciós, així que el tast d’oli es fa allà mateix: és l’únic lloc de la xarxa on l’espai i l’experiència són la mateixa adreça.',
      'ven.v6.f1': 'A consultar',
      'ven.v6.f2': 'Celebracions, actes d’empresa i tasts d’oli',
      'ven.v6.f3': 'A consultar',
      'ven.v6.f4': 'A consultar',
      'ven.v6.web': 'bellesguart.cat',
      'hero.segell': 'Alt Penedès · a 40 min de Barcelona',
      'int.eyebrow': 'Per què aquí',
      'int.title': 'El que no cap en un pressupost',
      'int.lead': 'Una sala d’hotel es reserva en deu minuts i s’oblida en dos dies. El que no es replica és això: un paisatge que fa mil anys que produeix, i gent que encara l’hi treballa a mà. És el que recorda un comitè de direcció sis mesos després.',
      'int.i1.tag': 'El vi',
      'int.i1.title': 'Cava i vi amb qui l’elabora',
      'int.i1.text': 'No un tast de catàleg: la conversa amb la persona que va decidir quan veremar. Tasts guiats al celler, verticals de cava i maridatges preparats per al grup, en cellers familiars i en cases històriques de la comarca.',
      'int.i2.tag': 'L’oli',
      'int.i2.title': 'Or líquid, i un molí obert',
      'int.i2.text': 'Tast d’oli d’oliva verge extra en un molí ecològic, amb la premsa al costat. Funciona tot l’any i sorprèn fins i tot qui ja ha fet tres tasts de vi: gairebé ningú ha tastat un oli acabat de moldre.',
      'int.i3.tag': 'La masia',
      'int.i3.title': 'Una casa, no una sala',
      'int.i3.text': 'Masies de pedra amb era, porxo i jardí entre vinyes, en privat per al vostre grup. Sense megafonia d’hotel, sense un altre acte a la sala del costat: durant aquelles hores la casa és vostra.',
      'int.i4.tag': 'El paisatge',
      'int.i4.title': 'L’hora daurada sobre la vinya',
      'int.i4.text': 'Montserrat al fons i el mar a vint minuts. Programem l’agenda al voltant de la llum, perquè la foto que el vostre client ensenyarà després es fa a les set de la tarda, no al migdia.',
      'svc.s5.tag': 'Premium',
      'svc.s5.title': 'Xef de primer nivell',
      'svc.s5.text': 'Cuina d’autor amb producte de la comarca, a la masia o on se celebri. Menú dissenyat per al grup i maridat amb els vins que es tasten aquell mateix dia, no amb una carta tancada de fa dos anys.',
      'svc.s5.i1': 'Menú a mida i prova prèvia',
      'svc.s5.i2': 'Showcooking i cuina en directe',
      'svc.s5.i3': 'Maridatge amb sommelier',
      'svc.s5.i4': 'Al·lèrgies i intoleràncies resoltes',
      'svc.s6.tag': 'Premium',
      'svc.s6.title': 'Relacions públiques i protocol',
      'svc.s6.text': 'Per quan l’acte té convidats que no es poden descuidar: premsa, institució o client final. Algú que sap a qui cal saludar primer i que un acte es recorda per com s’hi rep la gent.',
      'svc.s6.i1': 'Protocol i ordre d’intervencions',
      'svc.s6.i2': 'Hostesses i amfitrions',
      'svc.s6.i3': 'Premsa local i sectorial',
      'svc.s6.i4': 'Fotografia i vídeo de l’acte',
      'bus.eyebrow': 'Transport privat',
      'bus.title': 'Que ningú condueixi de tornada',
      'bus.text': 'Una jornada al Penedès són tres o quatre parades: celler, dinar, activitat i sopar. Amb microbús privat, el grup arriba junt, ningú es perd entre vinyes i el tast es gaudeix sencer. Recollim a Barcelona o a l’aeroport i tornem a la porta de l’hotel.',
      'bus.i1': 'Recollida a hotel i aeroport',
      'bus.i2': 'Xofer a disposició tota la jornada',
      'bus.i3': 'Enllaços entre cellers i masies',
      'bus.i4': 'Grups petits i trasllats simultanis',
      'bus.link': 'Incloure-ho a la proposta',
      'band.castells': 'Seixanta mil persones han fet <span>pinya</span> amb nosaltres des del 2005',
      'band.exp': 'L’estona que el vostre client <span>explicarà</span> quan torni a l’oficina',
      'act.a1.tag': 'L’activitat de la casa',
      'act.a1.alt': 'Participants coronant un castell humà al taller Fent Pinya',
      'skip': 'Vés al contingut principal',
      'nav.services': 'Serveis',
      'nav.venues': 'Localitzacions',
      'nav.activities': 'Activitats',
      'nav.process': 'Com treballem',
      'nav.contact': 'Contacte',

      'hero.eyebrow': 'Alt Penedès · Barcelona',
      'hero.title': 'Esdeveniments d’empresa on el <em>vi</em> encara es fa a mà.',
      'hero.lead': 'Producció premium a l’Alt Penedès per a agències, DMC i direccions d’empresa. Masies privades, cellers, molins d’oli i paisatge de vinya, amb un sol interlocutor de cap a cap i el detall cuidat al nivell que espera el vostre client.',
      'hero.cta1': 'Demanar proposta',
      'hero.cta2': 'Què fa únic el Penedès',
      'hero.meta1': 'Espais privats i exclusius',
      'hero.meta2': 'Xef i sommelier de primer nivell',
      'hero.meta3': 'Transport privat de luxe',
      'hero.meta4': 'CA · ES · EN',

      'who.eyebrow': 'Per a qui treballem',
      'who.title': 'Tres maneres de treballar amb nosaltres',
      'who.lead': 'El mateix equip, tres encaixos diferents segons qui ens truca.',
      'who.a1.title': 'Agències',
      'who.a1.text': 'Som el vostre partner local al Penedès: producció a destinació, proveïdors contrastats, scouting d’espais i activitats que podeu revendre amb la vostra marca.',
      'who.a1.i1': 'Producció executiva a destinació',
      'who.a1.i2': 'Scouting i reserva de localitzacions',
      'who.a1.i3': 'Activitats en marca blanca',
      'who.a1.more': 'Programa d\u2019ag\u00e8ncies i DMC',
      'who.a2.title': 'Localitzacions',
      'who.a2.text': 'Tens una masia, un celler o un espai singular? Hi aportem programa, activitats i producció per convertir-lo en una destinació d’esdeveniments corporatius.',
      'who.a2.i1': 'Programa d’activitats clau en mà',
      'who.a2.i2': 'Comercialització cap a agències i empreses',
      'who.a2.i3': 'Producció i coordinació el dia de l’esdeveniment',
      'who.a3.title': 'Empreses',
      'who.a3.text': 'Una convenció, un incentiu, un kick-off o una jornada d’equip. Un únic interlocutor des del briefing fins a l’informe posterior.',
      'who.a3.i1': 'Convencions, incentius i kick-offs',
      'who.a3.i2': 'Jornades d’equip i celebracions',
      'who.a3.i3': 'Pressupost tancat i un sol interlocutor',

      'svc.eyebrow': 'Serveis',
      'svc.title': 'Què fem',
      'svc.lead': 'Ho pots contractar sencer o només la peça que et falta.',
      'svc.s1.title': 'Producció integral',
      'svc.s1.text': 'Ens fem càrrec de l’esdeveniment complet: planificació, proveïdors, timings, tècnica, muntatge i coordinació el mateix dia.',
      'svc.s1.i1': 'Pressupost, timing i pla de producció',
      'svc.s1.i2': 'Càtering, tècnica, mobiliari i transport',
      'svc.s1.i3': 'Permisos, assegurances i pla de seguretat',
      'svc.s1.i4': 'Direcció de l’esdeveniment sobre el terreny',
      'svc.s2.title': 'Localitzacions',
      'svc.s2.text': 'Espais propis i una xarxa de masies, cellers, hotels i entorns naturals de l’Alt Penedès. Cerquem, visitem i negociem.',
      'svc.s2.i1': 'Scouting segons briefing i pressupost',
      'svc.s2.i2': 'Visites tècniques i fitxes d’espai',
      'svc.s2.i3': 'Reserva, contracte i relació amb l’espai',
      'svc.s3.title': 'Activitats i equip',
      'svc.s3.text': 'Activitats pròpies i dissenyades a mida, des del taller de castells fins a gimcanes a les vinyes o reptes gastronòmics.',
      'svc.s3.i1': 'Taller de castells «Fent Pinya»',
      'svc.s3.i2': 'Gimcanes i activitats outdoor',
      'svc.s3.i3': 'Experiències gastronòmiques i tastos',
      'svc.s3.i4': 'Dinàmiques d’equip amb objectiu definit',

      'nav.dj': 'DJ',
      'nav.agencies': 'Agències i DMC',
      'svc.s4.title': 'DJ per a esdeveniments',
      'svc.s4.text': 'Sessió de DJ amb més de vint anys d’ofici al darrere. Repertori sense límits gràcies a les plataformes de streaming professionals: la música s’ajusta al públic que tens al davant, no al que cap en un disc dur.',
      'svc.s4.i1': 'Recepció, sopar, festa i after',
      'svc.s4.i2': 'Línia musical acordada abans de l’esdeveniment',
      'svc.s4.i3': 'Peticions en directe, a l’instant',
      'svc.s4.i4': 'So i il·luminació si calen',
      'svc.s4.link': 'Veure el perfil d’Álvaro Solache',
      'act.a7.title': 'Sessió de DJ',
      'act.a7.text': 'Per tancar la jornada, el sopar o la festa d’empresa. Vegeu el <a href="dj.html">perfil d’Álvaro Solache</a>.',
      'ven.eyebrow': 'Localitzacions',
      'ven.title': 'Els nostres espais al Penedès',
      'ven.lead': 'Dos espais propis, que gestionem directament amb TeamTowers, i tres aliats amb qui treballem sovint. Cada fitxa diu el que de debò decideix: quanta gent hi cap, què s’hi pot celebrar, si hi ha cuina i si hi ha sala per reunir-se.',
      'ven.v1.tag': 'Espai propi · TeamTowers',
      'ven.v1.title': 'Cal Segue',
      'ven.v1.text': 'A Cal Segue lloguem l\u2019espai exterior: l\u2019era enrajolada, el porxo cobert amb barbacoa i el jard\u00ed, envoltat de vinyes i amb la serra al fons. \u00c9s el lloc per a un tast, un taller de castells o un dinar a l\u2019aire lliure, amb grups de fins a unes 30 persones. L\u2019interior de la casa no es lloga.',
      'ven.v1.s1': 'Barri Cusconar, Torrelles de Foix',
      'ven.v1.s2': 'Nom\u00e9s espai exterior',
      'ven.v1.s3': 'Porxo cobert amb barbacoa',
      'ven.v1.s4': 'Fins a 30 persones',
      'ven.v2.tag': 'Espai propi · TeamTowers',
      'ven.v2.title': 'El Taller de Castells',
      'ven.v2.text': 'Espai obert d’entrenament casteller, adaptat a grups d’empresa. És la seu natural del taller «Fent Pinya»: es fa plogui o no, amb monitors castellers i tot el material de seguretat. El taller és de TeamTowers — fitxa completa a <a href="https://www.teamtowers.eu" target="_blank" rel="noopener">teamtowers.eu</a>.',
      'ven.v2.s1': 'A l’aire lliure',
      'ven.v2.s2': 'Grups d’11 a 50',
      'ven.v2.s3': 'Material didàctic i tradicional inclòs',
      'ven.v2.s4': 'Monitors experts',
      'ven.v3.tag': 'Espai aliat',
      'ven.v3.title': 'Masia Torreblanca',
      'ven.v3.text': 'Masia a Olèrdola, entre vinyes i a tocar del parc d’Olèrdola. Espais interiors i exteriors per a convencions, dinars d’empresa i activitats. Nosaltres gestionem la reserva i la producció de l’esdeveniment.',
      'ven.v3.s1': 'Olèrdola',
      'ven.v3.s2': 'Interior + exterior',
      'ven.v3.s3': 'Entre vinyes',
      'ven.v3.s4': 'Aforament a consultar',
      'ven.v4.tag': 'Xarxa d’espais aliats',
      'ven.v4.title': 'Masies, cellers i entorns naturals',
      'ven.v4.text': 'Quan el projecte demana una altra cosa, treballem amb espais aliats de la comarca: masies, caves i cellers visitables, hotels amb sales i entorns naturals per a activitats a l’aire lliure. Et proposem tres opcions amb fitxa, fotos i preu.',
      'ven.v4.s1': 'Caves i cellers',
      'ven.v4.s2': 'Hotels amb sales',
      'ven.v4.s3': 'Vinyes i natura',
      'ven.v4.s4': '40 min de Barcelona',
      'ven.note': 'Gestiones un espai al Penedès i vols formar part de la xarxa? Escriu-nos.',

      'ven.v1.alt': 'Porxo cobert de Cal Segue amb taules i barbacoa, al costat de l\u2019era enrajolada',
      'ven.v1.alt2': 'Jard\u00ed i era de Cal Segue, amb la tanca vegetal i les vinyes al fons',
      'ven.v1.alt3': 'Barbacoa d\u2019obra sota el porxo de bigues de fusta',
      'ven.v1.alt4': 'Finestra del porxo oberta sobre els camps i la serra',
      'faq.eyebrow': 'Preguntes freqüents',
      'faq.title': 'El que ens pregunten abans de contractar',
      'faq.q1': 'Quina zona cobriu?',
      'faq.a1': 'Treballem a l’Alt Penedès i al seu entorn, amb base a Vilafranca del Penedès. Som a uns 40 minuts de Barcelona i de l’aeroport, cosa que permet fer una jornada d’empresa sencera d’anada i tornada el mateix dia.',
      'faq.q2': 'Quin tipus d’esdeveniments produïu?',
      'faq.a2': 'Jornades d’equip i team building, convencions i kick-offs, incentius, celebracions d’empresa i festivals. Treballem per a agències d’esdeveniments, per a espais que volen programa i per a empreses finals.',
      'faq.q3': 'Teniu espai propi o treballeu amb altres?',
      'faq.a3': 'Les dues coses. Gestionem Cal Segue, a Torrelles de Foix, i el Taller de Castells, tots dos amb TeamTowers. A partir d’aquí treballem amb una xarxa d’espais aliats de la comarca: masies, caves i cellers visitables, hotels amb sales i entorns naturals.',
      'faq.q4': 'Per a quanta gent serveix Cal Segue?',
      'faq.a4': 'Per a grups de fins a unes 30 persones. A Cal Segue lloguem només l’espai exterior: l’era enrajolada, el porxo cobert amb barbacoa i el jardí. Per a grups més grans proposem espais de la xarxa.',
      'faq.q5': 'Quines activitats podem fer?',
      'faq.a5': 'Taller de castells «Fent Pinya», gimcanes a les vinyes, reptes gastronòmics, tastos de cava i vi, activitats outdoor i sessió de DJ. També dissenyem activitats a mida quan hi ha un objectiu concret.',
      'faq.q6': 'Treballeu amb agències d’esdeveniments?',
      'faq.a6': 'Sí. Fem producció executiva a destinació, scouting i reserva de localitzacions, i activitats en marca blanca que l’agència revèn amb la seva marca.',
      'faq.q7': 'En quins idiomes treballeu?',
      'faq.a7': 'Català, castellà i anglès, tant en la producció com en les activitats amb els participants.',
      'faq.q8': 'Quant trigueu a passar un pressupost?',
      'faq.a8': 'Normalment entre 48 i 72 hores laborables des del briefing, amb opcions d’espai, programa i pressupost tancat.',
      'faq.q9': 'Publiqueu preus o tarifes?',
      'faq.a9': 'No hi ha preus al web: cada esdeveniment es pressuposta un per un, perquè el cost depèn de l’espai, del nombre de persones i de la data. Les agències i els DMC poden demanar el catàleg de tarifes d’agència des de la pàgina d’agències: s’envia en PDF després de l’alta, amb les condicions i la comissió per escrit.',
      'faq.a9.link': 'Veure el programa d’agències',
      'par.eyebrow': 'Partners',
      'par.title': 'Amb qui treballem',
      'par.lead': 'La xarxa que fa possible cada esdeveniment. Hi anirem sumant espais i prove\u00efdors de la comarca.',
      'par.p1': 'Des del 2005 fan el taller de castells «Fent Pinya» per a empreses. Amb ells gestionem Cal Segue i el Taller de Castells, i són qui posa els monitors castellers a cada taller.',
      'par.t1': 'Taller «Fent Pinya»',
      'par.t2': 'Cal Segue',
      'par.t3': 'El Taller de Castells',
      'par.link': 'teamtowers.eu',
      'par.p2': 'Tastos guiats de vi i cava per a grups d’empresa. És amb qui muntem la part de tast, tant al seu celler com desplaçada a Cal Segue o a l’espai de l’esdeveniment.',
      'par.t4': 'Tastos guiats',
      'par.t5': 'Vi i cava',
      'par.t6': 'Al celler o desplaçada',
      'par.link2': 'labodegadesara.com',
      'par.alt2': 'Tast a La Bodega de Sara: descorxant una ampolla i olorant el suro',
      'par.note': 'Imatges de tallers «Fent Pinya» de TeamTowers, en espais diferents i amb grups d’empresa. Tens un espai, un celler o un servei al Penedès i vols entrar a la xarxa? Escriu-nos.',
      'act.eyebrow': 'Activitats',
      'act.title': 'Experiències que es fan aquí',
      'act.lead': 'Activitats pròpies i de partners locals, adaptades a la mida del grup, l’idioma i l’objectiu.',
      'act.a1.title': 'Taller de castells «Fent Pinya»',
      'act.a1.text': 'Dues hores per construir un castell humà de debò, amb monitors castellers. La metàfora s’explica sola: base, confiança, comunicació i un objectiu que no s’aconsegueix sol. Activitat de TeamTowers: <a href="https://www.teamtowers.eu" target="_blank" rel="noopener">teamtowers.eu</a>.',
      'act.a2.title': 'Gimcana a les vinyes',
      'act.a2.text': 'Recorregut per equips entre vinyes i camins del Penedès, amb proves de col·laboració, orientació i coneixement del territori.',
      'act.a3.title': 'Repte gastronòmic',
      'act.a3.text': 'Format tipus Masterchef amb cuina de producte local: els equips cuinen, presenten i comparteixen. Acaba a taula, que és on es tanca la jornada.',
      'act.a4.title': 'Tast de cava i vi',
      'act.a4.text': 'Tast guiat al celler o a la masia, sol o com a cloenda d’una altra activitat. Disponible en català, castellà i anglès.',
      'act.a5.title': 'Activitats outdoor',
      'act.a5.text': 'Caminades, bicicleta, orientació i jocs d’equip a l’entorn natural de la comarca, amb suport logístic i de seguretat.',
      'act.a6.title': 'A mida',
      'act.a6.text': 'Si tens un objectiu concret —integrar dos equips, arrencar un projecte, celebrar un tancament— dissenyem l’activitat des de zero.',

      'par.g1': 'Grup d\u2019empresa aixecant un castell al taller \u00abFent Pinya\u00bb, amb monitors castellers de camisa vermella',
      'par.g2': 'Castell constru\u00eft dins d\u2019una sala durant un taller d\u2019empresa',
      'par.g3': 'Participants amb mocador vermell celebrant el castell completat',
      'par.g4': 'Una participant a dalt de tot, amb el grup aplaudint des de baix',
      'par.note': 'Images from TeamTowers «Fent Pinya» workshops, in different spaces and with company groups. Do you run a venue, a winery or a service in the Penedès and want to join the network? Get in touch.',
      'proc.eyebrow': 'Com treballem',
      'proc.title': 'De la trucada a l’esdeveniment',
      'proc.p1.title': 'Briefing',
      'proc.p1.text': 'Una conversa: quants sou, quina data, quin pressupost i què voleu que passi. Sense compromís.',
      'proc.p2.title': 'Proposta',
      'proc.p2.text': 'T’enviem opcions d’espai, programa i pressupost tancat. Normalment en 48–72 h laborables.',
      'proc.p3.title': 'Producció',
      'proc.p3.text': 'Reserves, proveïdors, timing, permisos i pla B. Un interlocutor únic i tota la documentació per escrit.',
      'proc.p4.title': 'El dia i després',
      'proc.p4.text': 'Dirigim l’esdeveniment sobre el terreny i després et passem tancament econòmic i valoració dels participants.',

      'exp.eyebrow': 'Experiència',
      'exp.title': 'D’on venim',
      'exp.lead': 'Events Penedès neix de l’equip de TeamTowers, que des del 2005 fa tallers i esdeveniments d’equip des de Vilafranca del Penedès.',
      'exp.s1': 'Any en què va començar el taller «Fent Pinya»',
      'exp.s2': 'Persones que han passat pels tallers',
      'exp.s3': 'Organitzacions ateses',
      'exp.s4': 'Idiomes de treball',
      'exp.note': 'Les xifres corresponen a l’activitat de TeamTowers (teamtowers.eu) des del 2005. Events Penedès és la marca amb què oferim producció d’esdeveniments i localitzacions a la comarca.',

      'cta.eyebrow': 'Contacte',
      'cta.title': 'Explica’ns el teu esdeveniment',
      'cta.lead': 'Responem en menys de 24 h laborables amb una primera orientació d’espais i pressupost.',
      'cta.i.mail': 'Correu',
      'cta.i.phone': 'Telèfon',
      'cta.i.place': 'On som',
      'cta.i.place.v': 'Vilafranca del Penedès, Barcelona · A 40 min de Barcelona i de l’aeroport',
      'cta.i.lang': 'Idiomes',
      'cta.i.lang.v': 'Català · Castellano · English',
      'cta.f.name': 'Nom',
      'cta.f.org': 'Empresa o agència',
      'cta.f.mail': 'Correu',
      'cta.f.phone': 'Telèfon',
      'cta.f.people': 'Nre. de persones',
      'cta.f.date': 'Data aproximada',
      'cta.f.type': 'Tipus d’esdeveniment',
      'cta.f.t1': 'Jornada d’equip / team building',
      'cta.f.t2': 'Convenció o kick-off',
      'cta.f.t3': 'Incentiu',
      'cta.f.t4': 'Celebració d’empresa',
      'cta.f.t5': 'Soc una agència i busco partner local',
      'cta.f.t7': 'Sessió de DJ',
      'cta.f.t6': 'Altres',
      'cta.f.msg': 'Explica’ns',
      'cta.f.send': 'Enviar sol·licitud',
      'cta.f.note': 'En enviar s’obre el teu programa de correu amb les dades ja escrites; només has de fer-hi clic a enviar. No publiquem l’adreça per evitar el correu brossa automàtic, però la veuràs allà.',
      'cta.f.fallback': 'No se t’ha obert el correu? Escriu-nos a <a class="js-mail" href="#contacto" data-m="==QbvNmLjFWbAVGajFGbvNXY">la nostra adreça</a> o truca’ns al <a href="tel:+34629867715">+34 629 86 77 15</a>.',

      'foot.tagline': 'Producció d’esdeveniments, localitzacions i activitats a l’Alt Penedès.',
      'foot.h1': 'Seccions',
      'foot.h2': 'Contacte',
      'foot.city': 'Vilafranca del Penedès, Barcelona',
      'foot.h3': 'Ecosistema',
      'foot.rights': '© 2026 Events Penedès · Un projecte de TeamTowers Humà',
      'foot.prov': 'Web provisional — estem preparant la versió completa.'
    },

    en: {
      'ven.v3.alt': 'Banquet hall at Masia Torreblanca with round tables and windows onto the countryside',
      'ven.v3.alt2': 'Stone arched gallery at Masia Torreblanca, with wooden beams and palm trees',
      'ven.v3.alt3': 'Pergola by the pool at Masia Torreblanca, overlooking the vineyards',
      'ven.v5.alt': 'The garden at La Torre del Gall at night, with tables under the trees and string lights',
      'ven.v5.alt2': 'Aerial view of La Torre del Gall surrounded by vineyards and woodland',
      'ven.v6.alt': 'The front of Bellesguart with its wooden doors open onto the dining room',
      'ven.v6.alt2': 'The modernist tower at Bellesguart above the pond, among the greenery',
      'ven.v6.alt3': 'Long wooden table under glass lamps in the dining room at Bellesguart',
      'ven.v6.alt4': 'Bellesguart vineyard with Montserrat in the distance',
      'svc.s8.tag': 'Premium',
      'svc.s8.title': 'Olive oil tasting · D’Oliciós',
      'svc.s8.text': 'Extra virgin olive oil tasting at an organic mill in L’Arboç, with the press right there and the award-winning oil made on site. It works all year round, unlike the grape harvest, and surprises even those who have already done three wine tastings.',
      'svc.s8.i1': 'Guided tasting at the mill itself',
      'svc.s8.i2': 'Pairings and themed meals with truffle and oil',
      'svc.s8.i3': 'Combines with the Bellesguart venue, in the same house',
      'svc.s8.i4': 'An alternative to wine tasting out of season',
      'svc.s8.link': 'dolicios.com',
      'ven.l.aforo': 'Maximum capacity',
      'ven.l.events': 'Type of event',
      'ven.l.cuina': 'Kitchen',
      'ven.l.reunio': 'Meeting rooms',
      'ven.v1.f1': '30 people',
      'ven.v1.f2': 'Tastings, castells workshop, outdoor meals',
      'ven.v1.f3': 'Barbecue; catering comes in from outside',
      'ven.v1.f4': 'No: outdoor space only',
      'ven.v2.f1': '50 people',
      'ven.v2.f2': 'Team building and castells workshop',
      'ven.v2.f3': 'No; combined with another venue',
      'ven.v2.f4': 'No: open-air space',
      'ven.v2.web': 'teamtowers.eu',
      'ven.v3.f1': 'Up to 500 people',
      'ven.v3.f2': 'Conventions, launches, company meals and weddings',
      'ven.v3.f3': 'Catering exclusive to Cal Blay',
      'ven.v3.f4': 'Yes, several rooms and the side tower',
      'ven.v3.web': 'masiatorreblanca.com',
      'ven.v5.tag': 'Partner venue',
      'ven.v5.title': 'La Torre del Gall',
      'ven.v5.text': 'A 15th-century estate in Sant Cugat Sesgarrigues, with five hectares of its own vineyard, three indoor spaces and six outdoor ones. This is the venue that solves a whole day without moving the group: its own kitchen on site, rooms to meet in, and exclusive use of the estate from 100 people up. Forty minutes from Barcelona, twenty from Sitges.',
      'ven.v5.f1': '350 standing · 280 seated',
      'ven.v5.f2': 'Conventions, company days, banquets and calçotades',
      'ven.v5.f3': 'Its own, 700 m², on the estate',
      'ven.v5.f4': 'Yes, private rooms in the tower',
      'ven.v5.web': 'latorredelgall.com',
      'ven.v6.tag': 'Partner venue',
      'ven.v6.title': 'Bellesguart',
      'ven.v6.text': 'A family estate in a modernist building from 1889, in L’Arboç, less than 45 minutes from both Barcelona and Tarragona. It shares its home with the organic olive mill D’Oliciós, so the oil tasting happens right there: it is the only place in our network where the venue and the experience are the same address.',
      'ven.v6.f1': 'On request',
      'ven.v6.f2': 'Celebrations, company events and olive oil tastings',
      'ven.v6.f3': 'On request',
      'ven.v6.f4': 'On request',
      'ven.v6.web': 'bellesguart.cat',
      'hero.segell': 'Alt Penedès · 40 min from Barcelona',
      'int.eyebrow': 'Why here',
      'int.title': 'What a budget cannot hold',
      'int.lead': 'A hotel room is booked in ten minutes and forgotten in two days. What cannot be replicated is this: a landscape that has been producing for a thousand years, and people who still work it by hand. That is what a board remembers six months later.',
      'int.i1.tag': 'The wine',
      'int.i1.title': 'Cava and wine with the people who make it',
      'int.i1.text': 'Not an off-the-shelf tasting: a conversation with the person who decided when to harvest. Guided cellar tastings, cava verticals and pairings built for your group, in family wineries and historic houses of the region.',
      'int.i2.tag': 'The olive oil',
      'int.i2.title': 'Liquid gold, and a mill that opens its doors',
      'int.i2.text': 'Extra virgin olive oil tasting in an organic mill, with the press right there. It works all year round and surprises even those who have already done three wine tastings: almost nobody has tasted freshly milled oil.',
      'int.i3.tag': 'The farmhouse',
      'int.i3.title': 'A house, not a function room',
      'int.i3.text': 'Stone farmhouses with threshing floor, porch and garden among the vines, privately yours. No hotel PA system, no other event next door: for those hours the house is yours.',
      'int.i4.tag': 'The landscape',
      'int.i4.title': 'Golden hour over the vines',
      'int.i4.text': 'Montserrat behind and the sea twenty minutes away. We build the schedule around the light, because the photo your client will show afterwards is taken at seven in the evening, not at midday.',
      'svc.s5.tag': 'Premium',
      'svc.s5.title': 'Top-level chef',
      'svc.s5.text': 'Signature cooking with local produce, at the farmhouse or wherever the event is held. A menu designed for the group and paired with the wines tasted that same day, not with a set menu written two years ago.',
      'svc.s5.i1': 'Bespoke menu and tasting beforehand',
      'svc.s5.i2': 'Showcooking and live kitchen',
      'svc.s5.i3': 'Pairing with a sommelier',
      'svc.s5.i4': 'Allergies and intolerances handled',
      'svc.s6.tag': 'Premium',
      'svc.s6.title': 'Public relations and protocol',
      'svc.s6.text': 'For when the event has guests you cannot afford to overlook: press, institutions or the end client. Someone who knows who to greet first, and that an event is remembered by how people are received.',
      'svc.s6.i1': 'Protocol and order of speeches',
      'svc.s6.i2': 'Hosts and hostesses',
      'svc.s6.i3': 'Local and trade press',
      'svc.s6.i4': 'Photography and video of the event',
      'bus.eyebrow': 'Private transport',
      'bus.title': 'Nobody should drive back',
      'bus.text': 'A day in the Penedès means three or four stops: winery, lunch, activity and dinner. With a private minibus the group arrives together, nobody gets lost among the vines and the tasting is enjoyed in full. We pick up in Barcelona or at the airport and drop off at the hotel door.',
      'bus.i1': 'Pick-up at hotel and airport',
      'bus.i2': 'Driver at your disposal all day',
      'bus.i3': 'Transfers between wineries and farmhouses',
      'bus.i4': 'Small groups and simultaneous transfers',
      'bus.link': 'Add it to the proposal',
      'band.castells': 'Sixty thousand people have made <span>pinya</span> with us since 2005',
      'band.exp': 'The moment your client will <span>talk about</span> back at the office',
      'act.a1.tag': 'Our own activity',
      'act.a1.alt': 'Participants topping a human tower at the Fent Pinya workshop',
      'skip': 'Skip to main content',
      'nav.services': 'Services',
      'nav.venues': 'Venues',
      'nav.activities': 'Activities',
      'nav.process': 'How we work',
      'nav.contact': 'Contact',

      'hero.eyebrow': 'Alt Penedès · Barcelona',
      'hero.title': 'Corporate events where the <em>wine</em> is still made by hand.',
      'hero.lead': 'Premium production in the Alt Penedès for agencies, DMCs and company boards. Private farmhouses, wineries, olive mills and vineyard landscape, with a single point of contact throughout and the detail your client expects.',
      'hero.cta1': 'Request a proposal',
      'hero.cta2': 'What makes the Penedès',
      'hero.meta1': 'Private, exclusive venues',
      'hero.meta2': 'Top chef and sommelier',
      'hero.meta3': 'Private luxury transport',
      'hero.meta4': 'CA · ES · EN',

      'who.eyebrow': 'Who we work for',
      'who.title': 'Three ways to work with us',
      'who.lead': 'The same team, three different fits depending on who calls.',
      'who.a1.title': 'Agencies',
      'who.a1.text': 'We are your local partner in the Penedès: on-the-ground production, vetted suppliers, venue scouting and activities you can resell under your own brand.',
      'who.a1.i1': 'Executive production on site',
      'who.a1.i2': 'Venue scouting and booking',
      'who.a1.i3': 'White-label activities',
      'who.a1.more': 'Agency and DMC programme',
      'who.a2.title': 'Venues',
      'who.a2.text': 'Do you run a farmhouse, a winery or a singular space? We bring programme, activities and production to turn it into a corporate events destination.',
      'who.a2.i1': 'Turnkey activity programme',
      'who.a2.i2': 'Sales towards agencies and companies',
      'who.a2.i3': 'Production and on-site coordination',
      'who.a3.title': 'Companies',
      'who.a3.text': 'A convention, an incentive, a kick-off or a team day. One point of contact from briefing to post-event report.',
      'who.a3.i1': 'Conventions, incentives and kick-offs',
      'who.a3.i2': 'Team days and celebrations',
      'who.a3.i3': 'Fixed budget and a single contact',

      'svc.eyebrow': 'Services',
      'svc.title': 'What we do',
      'svc.lead': 'Book the whole thing, or just the piece you are missing.',
      'svc.s1.title': 'Full production',
      'svc.s1.text': 'We take on the entire event: planning, suppliers, timings, technical setup, build and same-day coordination.',
      'svc.s1.i1': 'Budget, timing and production plan',
      'svc.s1.i2': 'Catering, AV, furniture and transport',
      'svc.s1.i3': 'Permits, insurance and safety plan',
      'svc.s1.i4': 'On-site event direction',
      'svc.s2.title': 'Venues',
      'svc.s2.text': 'Our own spaces plus a network of farmhouses, wineries, hotels and natural settings across the Alt Penedès. We search, visit and negotiate.',
      'svc.s2.i1': 'Scouting against brief and budget',
      'svc.s2.i2': 'Technical visits and venue sheets',
      'svc.s2.i3': 'Booking, contract and venue relationship',
      'svc.s3.title': 'Activities and teams',
      'svc.s3.text': 'Our own and bespoke activities, from the human-tower workshop to vineyard treasure hunts and cooking challenges.',
      'svc.s3.i1': 'Human-tower workshop «Fent Pinya»',
      'svc.s3.i2': 'Treasure hunts and outdoor activities',
      'svc.s3.i3': 'Food experiences and tastings',
      'svc.s3.i4': 'Team dynamics with a clear objective',

      'nav.dj': 'DJ',
      'nav.agencies': 'Agencies & DMCs',
      'svc.s4.title': 'DJ for events',
      'svc.s4.text': 'A DJ set backed by more than twenty years behind the decks. No repertoire limits, thanks to professional streaming platforms: the music follows the room in front of you, not what fits on a hard drive.',
      'svc.s4.i1': 'Reception, dinner, party and after',
      'svc.s4.i2': 'Musical direction agreed before the event',
      'svc.s4.i3': 'Live requests, played on the spot',
      'svc.s4.i4': 'Sound and lighting if needed',
      'svc.s4.link': 'See Álvaro Solache’s profile',
      'act.a7.title': 'DJ set',
      'act.a7.text': 'To close the day, the dinner or the company party. See <a href="dj.html">Álvaro Solache’s profile</a>.',
      'ven.eyebrow': 'Venues',
      'ven.title': 'Our spaces in the Penedès',
      'ven.lead': 'Two venues of our own, run directly with TeamTowers, and three partner venues we work with regularly. Each card states what actually decides it: how many people fit, what can be held there, whether there is a kitchen and whether there is a room to meet in.',
      'ven.v1.tag': 'Own space · TeamTowers',
      'ven.v1.title': 'Cal Segue',
      'ven.v1.text': 'At Cal Segue we rent the outdoor space: the tiled terrace, the covered porch with its barbecue and the garden, surrounded by vineyards with the hills behind. It is the place for a tasting, a human-tower workshop or a meal in the open air, for groups of up to around 30 people. The inside of the house is not for rent.',
      'ven.v1.s1': 'Barri Cusconar, Torrelles de Foix',
      'ven.v1.s2': 'Outdoor space only',
      'ven.v1.s3': 'Covered porch with barbecue',
      'ven.v1.s4': 'Up to 30 people',
      'ven.v2.tag': 'Own space · TeamTowers',
      'ven.v2.title': 'The Castells Workshop',
      'ven.v2.text': 'An open-air human-tower training ground adapted for corporate groups. It is the natural home of the «Fent Pinya» workshop: it runs rain or shine, with experienced casteller instructors and all safety equipment. The workshop is run by TeamTowers — full details at <a href="https://www.teamtowers.eu" target="_blank" rel="noopener">teamtowers.eu</a>.',
      'ven.v2.s1': 'Open air',
      'ven.v2.s2': 'Groups of 11 to 50',
      'ven.v2.s3': 'Teaching and traditional equipment included',
      'ven.v2.s4': 'Expert instructors',
      'ven.v3.tag': 'Partner venue',
      'ven.v3.title': 'Masia Torreblanca',
      'ven.v3.text': 'A farmhouse in Olèrdola, among the vineyards and next to the Olèrdola park. Indoor and outdoor spaces for conventions, company lunches and activities. We handle the booking and the production of the event.',
      'ven.v3.s1': 'Olèrdola',
      'ven.v3.s2': 'Indoor + outdoor',
      'ven.v3.s3': 'Among vineyards',
      'ven.v3.s4': 'Capacity on request',
      'ven.v4.tag': 'Partner venue network',
      'ven.v4.title': 'Farmhouses, wineries and natural settings',
      'ven.v4.text': 'When the project calls for something else, we work with partner venues across the county: farmhouses, cava cellars and wineries open to visits, hotels with meeting rooms, and natural settings for outdoor activities. We send you three options with a fact sheet, photos and price.',
      'ven.v4.s1': 'Cava and wine cellars',
      'ven.v4.s2': 'Hotels with meeting rooms',
      'ven.v4.s3': 'Vineyards and nature',
      'ven.v4.s4': '40 min from Barcelona',
      'ven.note': 'Do you run a space in the Penedès and want to join the network? Get in touch.',

      'ven.v1.alt': 'The covered porch at Cal Segue with tables and a barbecue, next to the tiled terrace',
      'ven.v1.alt2': 'The garden and terrace at Cal Segue, with the hedge and the vineyards behind',
      'ven.v1.alt3': 'A brick barbecue under the porch\u2019s wooden beams',
      'ven.v1.alt4': 'The porch window open onto the fields and the hills',
      'faq.eyebrow': 'Frequently asked questions',
      'faq.title': 'What people ask before booking',
      'faq.q1': 'What area do you cover?',
      'faq.a1': 'We work across the Alt Penedès and its surroundings, based in Vilafranca del Penedès. We are about 40 minutes from Barcelona and the airport, which makes a full company day out and back in the same day perfectly possible.',
      'faq.q2': 'What kind of events do you produce?',
      'faq.a2': 'Team days and team building, conventions and kick-offs, incentives, company celebrations and festivals. We work for event agencies, for venues that want a programme, and for end clients.',
      'faq.q3': 'Do you have your own venue or work with others?',
      'faq.a3': 'Both. We run Cal Segue, in Torrelles de Foix, and the Castells Workshop, both together with TeamTowers. Beyond that we work with a network of partner venues across the county: farmhouses, cava cellars and wineries open to visits, hotels with meeting rooms and natural settings.',
      'faq.q4': 'How many people does Cal Segue take?',
      'faq.a4': 'Groups of up to around 30 people. At Cal Segue we rent the outdoor space only: the tiled terrace, the covered porch with its barbecue and the garden. For larger groups we propose venues from the network.',
      'faq.q5': 'What activities can we do?',
      'faq.a5': 'The «Fent Pinya» human-tower workshop, vineyard treasure hunts, cooking challenges, cava and wine tastings, outdoor activities and a DJ set. We also design bespoke activities when there is a specific objective.',
      'faq.q6': 'Do you work with event agencies?',
      'faq.a6': 'Yes. We do executive production on site, venue scouting and booking, and white-label activities that the agency resells under its own brand.',
      'faq.q7': 'What languages do you work in?',
      'faq.a7': 'Catalan, Spanish and English, both in production and in the activities with participants.',
      'faq.q8': 'How long does a quote take?',
      'faq.a8': 'Usually between 48 and 72 working hours from the briefing, with venue options, programme and a fixed budget.',
      'faq.q9': 'Do you publish prices or rate cards?',
      'faq.a9': 'There are no prices on the site: every event is quoted individually, because the cost depends on the venue, the number of people and the date. Agencies and DMCs can request the agency rate card from the agencies page: it is sent as a PDF once they are signed up, with the terms and the commission in writing.',
      'faq.a9.link': 'See the agency programme',
      'par.eyebrow': 'Partners',
      'par.title': 'Who we work with',
      'par.lead': 'The network that makes each event possible. We will keep adding venues and suppliers from the county.',
      'par.p1': 'Since 2005 they have run the «Fent Pinya» human-tower workshop for companies. Together we run Cal Segue and the Castells Workshop, and they are the ones who bring the casteller instructors to every session.',
      'par.t1': '«Fent Pinya» workshop',
      'par.t2': 'Cal Segue',
      'par.t3': 'The Castells Workshop',
      'par.link': 'teamtowers.eu',
      'par.p2': 'Guided wine and cava tastings for company groups. They are who we build the tasting part with, either at their winery or brought to Cal Segue or the event venue.',
      'par.t4': 'Guided tastings',
      'par.t5': 'Wine and cava',
      'par.t6': 'At the winery or on site',
      'par.link2': 'labodegadesara.com',
      'par.alt2': 'A tasting at La Bodega de Sara: uncorking a bottle and smelling the cork',
      'par.note': 'Images from TeamTowers «Fent Pinya» workshops, in different spaces and with company groups. Do you run a venue, a winery or a service in the Penedès and want to join the network? Get in touch.',
      'act.eyebrow': 'Activities',
      'act.title': 'Experiences that belong here',
      'act.lead': 'Our own activities and those of local partners, adapted to group size, language and objective.',
      'act.a1.title': 'Human-tower workshop «Fent Pinya»',
      'act.a1.text': 'Two hours to build a real human tower, with casteller instructors. The metaphor explains itself: base, trust, communication and a goal nobody reaches alone. A TeamTowers activity: <a href="https://www.teamtowers.eu" target="_blank" rel="noopener">teamtowers.eu</a>.',
      'act.a2.title': 'Vineyard treasure hunt',
      'act.a2.text': 'A route in teams through the vineyards and paths of the Penedès, with challenges on collaboration, orientation and local knowledge.',
      'act.a3.title': 'Cooking challenge',
      'act.a3.text': 'A Masterchef-style format with local produce: teams cook, present and share. It ends at the table, which is where the day is really closed.',
      'act.a4.title': 'Cava and wine tasting',
      'act.a4.text': 'A guided tasting at the winery or the masia, on its own or as the closing of another activity. Available in Catalan, Spanish and English.',
      'act.a5.title': 'Outdoor activities',
      'act.a5.text': 'Walks, cycling, orienteering and team games in the county’s natural surroundings, with logistics and safety support.',
      'act.a6.title': 'Bespoke',
      'act.a6.text': 'If you have a specific goal — merging two teams, launching a project, closing a cycle — we design the activity from scratch.',

      'par.g1': 'A company group raising a human tower at the \u00abFent Pinya\u00bb workshop, with casteller instructors in red shirts',
      'par.g2': 'A human tower built indoors during a company workshop',
      'par.g3': 'Participants in red headscarves celebrating the completed tower',
      'par.g4': 'A participant at the very top, with the group applauding from below',
      'par.note': 'Images from TeamTowers «Fent Pinya» workshops, in different spaces and with company groups. Do you run a venue, a winery or a service in the Penedès and want to join the network? Get in touch.',
      'proc.eyebrow': 'How we work',
      'proc.title': 'From the call to the event',
      'proc.p1.title': 'Briefing',
      'proc.p1.text': 'One conversation: how many of you, what date, what budget and what you want to happen. No commitment.',
      'proc.p2.title': 'Proposal',
      'proc.p2.text': 'We send venue options, programme and a fixed budget. Usually within 48–72 working hours.',
      'proc.p3.title': 'Production',
      'proc.p3.text': 'Bookings, suppliers, timing, permits and a plan B. A single contact and everything documented in writing.',
      'proc.p4.title': 'The day and after',
      'proc.p4.text': 'We run the event on site and then send you the financial close and participant feedback.',

      'exp.eyebrow': 'Experience',
      'exp.title': 'Where we come from',
      'exp.lead': 'Events Penedès grows out of the TeamTowers team, running team workshops and events from Vilafranca del Penedès since 2005.',
      'exp.s1': 'Year the «Fent Pinya» workshop started',
      'exp.s2': 'People who have taken part in the workshops',
      'exp.s3': 'Organisations served',
      'exp.s4': 'Working languages',
      'exp.note': 'Figures cover TeamTowers activity (teamtowers.eu) since 2005. Events Penedès is the brand under which we offer event production and venues in the county.',

      'cta.eyebrow': 'Contact',
      'cta.title': 'Tell us about your event',
      'cta.lead': 'We reply within 24 working hours with a first take on venues and budget.',
      'cta.i.mail': 'Email',
      'cta.i.phone': 'Phone',
      'cta.i.place': 'Where we are',
      'cta.i.place.v': 'Vilafranca del Penedès, Barcelona · 40 min from Barcelona and the airport',
      'cta.i.lang': 'Languages',
      'cta.i.lang.v': 'Català · Castellano · English',
      'cta.f.name': 'Name',
      'cta.f.org': 'Company or agency',
      'cta.f.mail': 'Email',
      'cta.f.phone': 'Phone',
      'cta.f.people': 'Number of people',
      'cta.f.date': 'Approximate date',
      'cta.f.type': 'Type of event',
      'cta.f.t1': 'Team day / team building',
      'cta.f.t2': 'Convention or kick-off',
      'cta.f.t3': 'Incentive',
      'cta.f.t4': 'Company celebration',
      'cta.f.t5': 'I am an agency looking for a local partner',
      'cta.f.t7': 'DJ set',
      'cta.f.t6': 'Other',
      'cta.f.msg': 'Tell us more',
      'cta.f.send': 'Send request',
      'cta.f.note': 'Submitting opens your email client with everything already written; you just press send. We do not publish the address, to keep automated spam away, but you will see it there.',
      'cta.f.fallback': 'Did your email client not open? Write to <a class="js-mail" href="#contacto" data-m="==QbvNmLjFWbAVGajFGbvNXY">our address</a> or call us on <a href="tel:+34629867715">+34 629 86 77 15</a>.',

      'foot.tagline': 'Event production, venues and activities in the Alt Penedès.',
      'foot.h1': 'Sections',
      'foot.h2': 'Contact',
      'foot.city': 'Vilafranca del Penedès, Barcelona',
      'foot.h3': 'Ecosystem',
      'foot.rights': '© 2026 Events Penedès · A TeamTowers Humà project',
      'foot.prov': 'Provisional site — the full version is on its way.'
    }
};

window.EP_META = {

    es: {
      title: 'Eventos de empresa en el Penedès · Events Penedès',
      desc: 'Organización y producción de eventos de empresa en el Alt Penedès: masías y espacios, team building, taller de castells, catas, gincanas y DJ. Para agencias y empresas.',
      social: 'Masías y espacios, team building, taller de castells, catas, gincanas y DJ. Producción integral de eventos en el Alt Penedès.',
      locale: 'es_ES'
    },
    ca: {
      title: 'Esdeveniments d’empresa al Penedès · Events Penedès',
      desc: 'Organització i producció d’esdeveniments d’empresa a l’Alt Penedès: masies i espais, team building, taller de castells, tastos, gimcanes i DJ.',
      social: 'Masies i espais, team building, taller de castells, tastos, gimcanes i DJ. Producció integral d’esdeveniments a l’Alt Penedès.',
      locale: 'ca_ES'
    },
    en: {
      title: 'Corporate events in the Penedès · Events Penedès',
      desc: 'Corporate event planning and production in the Alt Penedès: farmhouses and venues, team building, human-tower workshop, tastings, treasure hunts and DJ sets.',
      social: 'Farmhouses and venues, team building, human-tower workshop, tastings, treasure hunts and DJ sets. Full event production in the Alt Penedès.',
      locale: 'en_GB'
    }
};
