/* =============================================================================
   GENERADO por tools/build-kit.mjs · no editar aquí.
   Textos del kit para agencias en catalán e inglés: los del catálogo, en marca
   blanca, y los fijos de la página.
   ========================================================================== */
window.EP_I18N = {

  ca: {
    'skip': 'Vés al contingut principal',
    'nav.services': 'Serveis',
    'nav.venues': 'Localitzacions',
    'nav.activities': 'Activitats',
    'nav.process': 'Com treballem',
    'nav.dj': 'DJ',
    'nav.contact': 'Contacte',
    'nav.agencies': 'Agències i DMC',
    'nav.brief': 'Demanar proposta',
    'foot.priv': 'Avís de privacitat',
    'foot.res': 'Recursos',
    'foot.tagline': 'Producció d’esdeveniments, localitzacions i activitats a l’Alt Penedès.',
    'foot.h1': 'Seccions',
    'foot.h2': 'Contacte',
    'foot.h3': 'Ecosistema',
    'foot.city': 'Torrelles de Foix, Barcelona',
    'foot.rights': '© 2026 Events Penedès · Un projecte de TeamTowers Humà',
    'kit.crumb': 'Agències',
    'kit.crumb2': 'Kit per a la teva proposta',
    'kit.eyebrow': 'Per a agències i DMC',
    'kit.title': 'Kit per a la teva proposta',
    'kit.lead': 'Textos i fotos per muntar la teva proposta amb la teva marca. Sense el nostre nom ni el dels proveïdors: copia’ls tal qual o canvia’ls al teu gust.',
    'kit.note': 'Aquí no hi ha preus. Les tarifes d’agència s’envien després de l’alta.',
    'kit.cta': 'Demanar les tarifes',
    'kit.t.eyebrow': 'Textos',
    'kit.t.title': 'El que pots oferir',
    'kit.copiar': 'Copiar el text',
    'kit.f.eyebrow': 'Fotos',
    'kit.f.title': 'Per a la proposta',
    'kit.f.lead': 'Obre-les i desa-les. Fes-les servir només en propostes als teus clients, no al teu web ni a xarxes.',
    'kit.f.1': 'Grup aixecant un castell',
    'kit.f.2': 'Castell dins d’una sala',
    'kit.f.3': 'Celebració del grup',
    'kit.f.4': 'Participant al capdamunt',
    'kit.f.5': 'Masia: porxo cobert i era',
    'kit.f.6': 'Masia: jardí amb les vinyes al fons',
    'kit.o.fent-pinya.n': 'Taller de castells «Fent Pinya»',
    'kit.o.fent-pinya.d': 'Dues hores per construir un castell humà de debò, amb monitors castellers. La metàfora s’explica sola: base, confiança, comunicació i un objectiu que no s’aconsegueix sol.',
    'kit.o.cata-vino-cava.n': 'Tast de cava i vi',
    'kit.o.cata-vino-cava.d': 'Tast guiat al celler o a la masia, sol o com a cloenda d’una altra activitat. Disponible en català, castellà i anglès.',
    'kit.o.cata-aceite.n': 'Tast d’oli',
    'kit.o.cata-aceite.d': 'Tast d’oli d’oliva verge extra en un molí ecològic de l’Arboç, amb la premsa al costat i l’oli premiat que s’hi elabora. Funciona tot l’any, a diferència de la verema, i sorprèn fins i tot qui ja ha fet tres tasts de vi.',
    'kit.o.gincana-vinyes.n': 'Gimcana a les vinyes',
    'kit.o.gincana-vinyes.d': 'Recorregut per equips entre vinyes i camins del Penedès, amb proves de col·laboració, orientació i coneixement del territori.',
    'kit.o.reto-gastronomico.n': 'Repte gastronòmic',
    'kit.o.reto-gastronomico.d': 'Format tipus Masterchef amb cuina de producte local: els equips cuinen, presenten i comparteixen. Acaba a taula, que és on es tanca la jornada.',
    'kit.o.outdoor.n': 'Activitats outdoor',
    'kit.o.outdoor.d': 'Caminades, bicicleta, orientació i jocs d’equip a l’entorn natural de la comarca, amb suport logístic i de seguretat.',
    'kit.o.chef-autor.n': 'Xef de primer nivell',
    'kit.o.chef-autor.d': 'Cuina d’autor amb producte de la comarca, a la masia o on se celebri. Menú dissenyat per al grup i maridat amb els vins que es tasten aquell mateix dia, no amb una carta tancada de fa dos anys.',
    'kit.o.rrpp-protocolo.n': 'Relacions públiques i protocol',
    'kit.o.rrpp-protocolo.d': 'Per quan l’acte té convidats que no es poden descuidar: premsa, institució o client final. Algú que sap a qui cal saludar primer i que un acte es recorda per com s’hi rep la gent.',
    'kit.o.dj-sesion.n': 'DJ per a esdeveniments',
    'kit.o.dj-sesion.d': 'Sessió de DJ amb més de vint anys d’ofici al darrere. Repertori sense límits gràcies a les plataformes de streaming professionals: la música s’ajusta al públic que tens al davant, no al que cap en un disc dur.',
    'kit.o.microbus.n': 'Que ningú condueixi de tornada',
    'kit.o.microbus.d': 'Una jornada al Penedès són tres o quatre parades: celler, dinar, activitat i sopar. Amb microbús privat, el grup arriba junt, ningú es perd entre vinyes i el tast es gaudeix sencer. Recollim a Barcelona o a l’aeroport i tornem a la porta de l’hotel.'
  },

  en: {
    'skip': 'Skip to main content',
    'nav.services': 'Services',
    'nav.venues': 'Venues',
    'nav.activities': 'Activities',
    'nav.process': 'How we work',
    'nav.dj': 'DJ',
    'nav.contact': 'Contact',
    'nav.agencies': 'Agencies & DMCs',
    'nav.brief': 'Request a proposal',
    'foot.priv': 'Privacy notice',
    'foot.res': 'Resources',
    'foot.tagline': 'Event production, venues and activities in the Alt Penedès.',
    'foot.h1': 'Sections',
    'foot.h2': 'Contact',
    'foot.h3': 'Ecosystem',
    'foot.city': 'Torrelles de Foix, Barcelona',
    'foot.rights': '© 2026 Events Penedès · A TeamTowers Humà project',
    'kit.crumb': 'Agencies',
    'kit.crumb2': 'Kit for your proposal',
    'kit.eyebrow': 'For agencies and DMCs',
    'kit.title': 'Kit for your proposal',
    'kit.lead': 'Texts and photos to build your proposal under your own brand. Without our name or our suppliers’: copy them as they are or adapt them.',
    'kit.note': 'There are no prices here. Agency rates are sent after sign-up.',
    'kit.cta': 'Request the rates',
    'kit.t.eyebrow': 'Texts',
    'kit.t.title': 'What you can offer',
    'kit.copiar': 'Copy the text',
    'kit.f.eyebrow': 'Photos',
    'kit.f.title': 'For your proposal',
    'kit.f.lead': 'Open and save them. Use them only in proposals to your clients, not on your website or social media.',
    'kit.f.1': 'Group raising a human tower',
    'kit.f.2': 'Human tower inside a hall',
    'kit.f.3': 'The group celebrating',
    'kit.f.4': 'Participant at the top',
    'kit.f.5': 'Farmhouse: covered porch and threshing floor',
    'kit.f.6': 'Farmhouse: garden with the vineyards behind',
    'kit.o.fent-pinya.n': 'Human-tower workshop «Fent Pinya»',
    'kit.o.fent-pinya.d': 'Two hours to build a real human tower, with casteller instructors. The metaphor explains itself: base, trust, communication and a goal nobody reaches alone.',
    'kit.o.cata-vino-cava.n': 'Cava and wine tasting',
    'kit.o.cata-vino-cava.d': 'A guided tasting at the winery or the masia, on its own or as the closing of another activity. Available in Catalan, Spanish and English.',
    'kit.o.cata-aceite.n': 'Olive oil tasting',
    'kit.o.cata-aceite.d': 'Extra virgin olive oil tasting at an organic mill in L’Arboç, with the press right there and the award-winning oil made on site. It works all year round, unlike the grape harvest, and surprises even those who have already done three wine tastings.',
    'kit.o.gincana-vinyes.n': 'Vineyard treasure hunt',
    'kit.o.gincana-vinyes.d': 'A route in teams through the vineyards and paths of the Penedès, with challenges on collaboration, orientation and local knowledge.',
    'kit.o.reto-gastronomico.n': 'Cooking challenge',
    'kit.o.reto-gastronomico.d': 'A Masterchef-style format with local produce: teams cook, present and share. It ends at the table, which is where the day is really closed.',
    'kit.o.outdoor.n': 'Outdoor activities',
    'kit.o.outdoor.d': 'Walks, cycling, orienteering and team games in the county’s natural surroundings, with logistics and safety support.',
    'kit.o.chef-autor.n': 'Top-level chef',
    'kit.o.chef-autor.d': 'Signature cooking with local produce, at the farmhouse or wherever the event is held. A menu designed for the group and paired with the wines tasted that same day, not with a set menu written two years ago.',
    'kit.o.rrpp-protocolo.n': 'Public relations and protocol',
    'kit.o.rrpp-protocolo.d': 'For when the event has guests you cannot afford to overlook: press, institutions or the end client. Someone who knows who to greet first, and that an event is remembered by how people are received.',
    'kit.o.dj-sesion.n': 'DJ for events',
    'kit.o.dj-sesion.d': 'A DJ set backed by more than twenty years behind the decks. No repertoire limits, thanks to professional streaming platforms: the music follows the room in front of you, not what fits on a hard drive.',
    'kit.o.microbus.n': 'Nobody should drive back',
    'kit.o.microbus.d': 'A day in the Penedès means three or four stops: winery, lunch, activity and dinner. With a private minibus the group arrives together, nobody gets lost among the vines and the tasting is enjoyed in full. We pick up in Barcelona or at the airport and drop off at the hotel door.'
  }
};

window.EP_META = {
  "es": {
    "title": "Kit para agencias · Events Penedès",
    "desc": "Textos y fotos en marca blanca para agencias y DMC que trabajan con Events Penedès.",
    "social": "Textos y fotos en marca blanca para tu propuesta.",
    "locale": "es_ES"
  },
  "ca": {
    "title": "Kit per a agències · Events Penedès",
    "desc": "Textos i fotos en marca blanca per a agències i DMC que treballen amb Events Penedès.",
    "social": "Textos i fotos en marca blanca per a la teva proposta.",
    "locale": "ca_ES"
  },
  "en": {
    "title": "Agency kit · Events Penedès",
    "desc": "White-label texts and photos for agencies and DMCs working with Events Penedès.",
    "social": "White-label texts and photos for your proposal.",
    "locale": "en_GB"
  }
};
